Module7 task1
htmlacademy-react/877447-six-cities-10 pull request #8
Opened 2022-08-25 21:17 UTC by Ramitsan

2022-08-26 09:13 UTC, yurylavrukhin requested changes
👍

2022-08-26 09:13 UTC, yurylavrukhin commented on project/src/services/api.ts
> +      if (error.response && shouldDisplayError(error.response)) {
давай выфильтровывать ошибку если чувак не авторизован — это не ошибка

сейчас если зайти на главную неавторизованным — юзер видит ошибку, это плохой пользовательский опыт

2022-08-26 09:13 UTC, yurylavrukhin commented on project/src/components/header/header.tsx
> +                    <span className="header__user-name user__name">Oliver.conner@gmail.com</span>
давай показывать реальный емейл юзера (получить его можно от сервера, сложить в стор, и отрисовать)

2022-08-26 15:57 UTC, Ramitsan commented on project/src/components/header/header.tsx
> +                    <span className="header__user-name user__name">Oliver.conner@gmail.com</span>
Исправила

2022-08-26 15:57 UTC, Ramitsan commented on project/src/services/api.ts
> +      if (error.response && shouldDisplayError(error.response)) {
Исправила

2022-08-27 09:37 UTC, yurylavrukhin approved these changes
🚀 🚀 🚀

2022-08-27 09:38 UTC, merged